# Generated by Django 4.2.26 on 2025-11-27 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Passport number must contain only capital letters and digits.', regex='^[A-Z0-9]+$')]),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter phone number in this format: +631234567890. This accepts up to 15 digits.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
