# Generated by Django 5.2.8 on 2025-11-28 10:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Passenger', '0002_passenger_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('iata_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='IATA code must be exactly three uppercase letters (A–Z).', regex='^[A-Z]{3}$')], verbose_name='IATA code')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='Bookings.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='Bookings.city')),
            ],
            options={
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_code', models.CharField(help_text='Format: MA 800', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message="Flight code must be in format 'MA 800' (MA + space + 3 digits).", regex='^MA \\d{3}$')], verbose_name='Flight Code')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('base_fare', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.route')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now_add=True)),
                ('booking_ref', models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True)),
                ('baggage_allowance_qty', models.PositiveIntegerField(default=0)),
                ('travel_insurance', models.BooleanField(default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Passenger.passenger')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Bookings.flight')),
            ],
            options={
                'unique_together': {('passenger', 'flight')},
            },
        ),
    ]
