# Generated by Django 4.2.26 on 2025-11-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='baggage_allowance_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Baggage allowance'),
        ),
    ]
