# Generated by Django 5.2.8 on 2025-11-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
        ('Passenger', '0002_passenger_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('passenger', 'flight')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='base_fare',
        ),
    ]
