# Generated by Django 4.2.26 on 2025-12-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_alter_booking_baggage_allowance_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='Booking reference'),
        ),
    ]
